### ISSUE TITLE
Sticker Capsules

### ISSUE THREAD

**Issue by Nzxtime** [cantryDev/CSGOCaseStatsViewerV2#1]
Is there a way to include Sticker Capsules?

**Comment by cantryDev** [comment]
It should?
Select unbox analysis.
Select capsules

**Comment by Nzxtime** [comment]
Somehow Gold Stickers are not getting registered for me (redid the data-fetching). Logs: https://gist.github.com/Nzxtime/1ade809db32ff5ea490e013bea39ec44

Market History of unboxing: https://i.imgur.com/cWwvDaO.png

**Comment by cantryDev** [comment]
Okay this is another problem.
Which has nothing to do with the sticker capsules so will be disscussed here.
https://github.com/cantryDev/CSGOCaseStatsViewerV2/issues/3
