### ISSUE TITLE
I can't seem to trigger the commands because of an outdated java runtime version?

### ISSUE THREAD

**Issue by Khazilla** [cantryDev/CSGOCaseStatsViewerV2#12]
I am using windows 11, is that the issue?
![java](https://github.com/cantryDev/CSGOCaseStatsViewerV2/assets/141881577/d0cf584b-62ad-462b-bd24-4e5b28ae92af)

**Comment by Squiddy211** [comment]
Hi, 

I had the same issue, to fix this you have to install java 11 [here](https://www.oracle.com/au/java/technologies/javase/jdk11-archive-downloads.html) , or just search java 11 and download the developer pack then you should be all good

**Comment by cantryDev** [comment]
As described in the requirements you need Java 11 or higher to run it
