### ISSUE TITLE
Error: Unable to access jarfile CSGOCaseStatsViewerV2-1.0.3-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by zapTap6** [cantryDev/CSGOCaseStatsViewerV2#14]
I followed every single step,i tried to download it again,extract to different locations.
Same with v1 and v2 :/

**Comment by ViceBooster** [comment]
I get this as well, on windows 11 
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
Java HotSpot(TM) Client VM (build 25.381-b09, mixed mode, sharing)

**Comment by Sebastiony** [comment]
I had this issue - but its cause i clicked the wrong download. Could be the same for you.

Make sure you're not downloading the asset but the top link 
![image](https://github.com/cantryDev/CSGOCaseStatsViewerV2/assets/69179091/ccf9c673-d16a-40fe-bc4b-2291c5351d08)

Make sure its not the bottom two "Assets" But the top link called "[Download CSGOCaseStatsViewerV2-1.0.3.zip](https://github.com/cantryDev/CSGOCaseStatsViewerV2/files/12136415/CSGOCaseStatsViewerV2-1.0.3.zip)"
