### ISSUE TITLE
Exception in thread "main" java.lang.unsupportedClassVersionError

### ISSUE THREAD

**Issue by embl0** [cantryDev/CSGOCaseStatsViewerV2#15]
![image_2023-09-17_121132625](https://github.com/cantryDev/CSGOCaseStatsViewerV2/assets/145290809/588d7bf2-3717-4aa6-b557-1f61ac30718b)
I've updated Java, but I'm unsure what the problem actually is.

**Comment by cantryDev** [comment]
Seems like you old java version still get selected.

If you execute cmd.exe and input "java -version" it will probably still say 8
