### ISSUE TITLE
Couldn't find unboxing type from :Kilowatt Case

### ISSUE THREAD

**Issue by happyharrysco1** [cantryDev/CSGOCaseStatsViewerV2#21]
HI, when parsing history that includes the new Kilowatt case or the new ambush sticker capsule it can't find the unboxing type and as such i think it skews the results when checking case opening stats, logs in the results look like 

Couldnt find unboxing type from:Ambush Sticker Capsule
Couldnt find unboxing type from:Kilowatt Case

**Comment by cantryDev** [comment]
Fixed in https://github.com/cantryDev/CSGOCaseStatsViewerV2/releases/tag/1.0.4
