### ISSUE TITLE
Error with Jarfile

### ISSUE THREAD

**Issue by CoinflipPirate** [cantryDev/CSGOCaseStatsViewerV2#24]
Error: Unable to access jarfile CSGOCaseStatsViewerV2-1.0.4-jar-with-dependencies.jar

**Comment by Satalicious** [comment]
U need to compile it with maven in order to get the .jar file

**Comment by cantryDev** [comment]
Follow the steps: https://github.com/cantryDev/CSGOCaseStatsViewerV2?tab=readme-ov-file#usage
