### ISSUE TITLE
Error: Unable to access jarfile CSGOCaseStatsViewerV2-1.0.4-jar-with-dependencies.jar

### ISSUE THREAD

**Issue by nathan18889** [cantryDev/CSGOCaseStatsViewerV2#27]
happens everytime i open execute.bat

is it because i dont have java properly installed, i tried with the zulu-java- 11, 21, 22

**Comment by cantryDev** [comment]
![image](https://github.com/cantryDev/CSGOCaseStatsViewerV2/assets/16962714/1cbcfc09-84a1-4570-8ba8-4078da92363b)
https://github.com/cantryDev/CSGOCaseStatsViewerV2?tab=readme-ov-file#usage

You probably didnt follow one of these steps properly.

**Comment by nathan18889** [comment]
yep thank you, i opened wrong
