### ISSUE TITLE
Wrong odds on sticker capsules

### ISSUE THREAD

**Issue by ppoum** [cantryDev/CSGOCaseStatsViewerV2#4]
The current logic for the sticker capsule odds assumes that every capsule contains blue, purple, pink & red rarity stickers. However, many capsules that are not major related do not contain red-tier stickers and only contain blue, purple and pink stickers.

This makes the odds displayed at the end of an analysis wrong. For example, if a user opens 10 [capsules](https://csgostash.com/stickers/capsule/375/Espionage-Sticker-Capsule) that do not contain any red stickers, the output might look like

```
blue  |  10/10 (~ 100.0 %)  |  80.0%
...
red  |  0/10 (~ 0.0 %)  |  0.64%
```

when the output should look something more like

```
blue  |  10/10 (~ 100.0 %)  |  ?%
...
red  |  0/0 (~ 0.0 %)  |  0%
```

I'm not quite sure how the odds change for capsules that do not contain red-tier stickers, and implementing more accurate odds calculation might not be worth the trouble. Perhaps warning the user of potentially wrong odds if they have opened 1 or more capsules that don't have red stickers could be a better solution.

**Comment by cantryDev** [comment]
Good point.
Will add a warning for this in the next release.

**Comment by cantryDev** [comment]
Released now. Thank you for your contribution.
