### ISSUE TITLE
Curser Found

### ISSUE THREAD

**Issue by Sapplejacks** [cantryDev/CSGOCaseStatsViewerV2#5]
I've followed every step and made sure I've downloaded the correct zips and ran the right .bats. When I get to pasting the javascript in the console of inspect element I get a blank for cursor found. Am I just SOL? Or is there a legitimate way to fix this. I can't find any solutions on from google and would've liked to see my case history but can't figure this out.

**Comment by cantryDev** [comment]
Check the readme before opening a ticket.
https://github.com/cantryDev/CSGOCaseStatsViewerV2#cursor-empty
